-- Ejeutar en Supabase SQL Editor

-- 1. Tabla de Roles (Ya la tenías, la dejo por si acaso)
CREATE TABLE IF NOT EXISTS public.roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- 2. Tabla de Vinculación Usuario-Rol
CREATE TABLE IF NOT EXISTS public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role_id BIGINT REFERENCES public.roles(id) ON DELETE CASCADE,
  UNIQUE(user_id, role_id)
);

-- 3. Tabla de Perfiles de Usuario (NUEVO)
-- Esta tabla gestionará el estado de aprobación
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  status TEXT DEFAULT 'Pendiente' CHECK (status IN ('Pendiente', 'Aprobado', 'Cancelado')),
  full_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Trigger para Crear Perfil Automáticamente (NUEVO)
-- Cuando alguien se registra en Auth, se crea aquí como 'Pendiente'
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, status)
  VALUES (new.id, new.email, 'Pendiente');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Eliminar trigger si existe para evitar conflictos al recrear
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. Insertar Roles iniciales
INSERT INTO public.roles (name) VALUES
('Administracion'),
('Almacen'),
('Logistica'),
('Produccion'),
('Diseño'),
('Ventas'),
('Compras'),
('Recursos Humanos'),
('Contabilidad')
ON CONFLICT (name) DO NOTHING;

-- 6. Habilitar Seguridad (RLS)
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 7. Crear Políticas de Acceso
-- Roles: Lectura pública para autenticados
CREATE POLICY "Roles visibles para autenticados" ON public.roles
  FOR SELECT TO authenticated USING (true);

-- User Roles: Usuario ve sus propios roles
CREATE POLICY "Usuario ve sus propios roles" ON public.user_roles
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

-- Perfiles: Usuario ve su propio perfil
CREATE POLICY "Usuario ve su propio perfil" ON public.profiles
  FOR SELECT TO authenticated USING (auth.uid() = id);

-- Perfiles: Admin/Roles especiales deberían poder ver todo (Por ahora lo dejamos así para que funcione el login básico)
-- NOTA IMPORTANTISIMA:
-- Para que el ADMIN pueda aprobar usuarios, necesitará una politica especial.
-- Por ahora, como vas a aprobar manualmente desde Supabase Dashboard (Table Editor), 
-- no necesitas política extra, el Dashboard tiene acceso total.
